---
- name: Download multiple cloud images
  hosts: proxmox_prd
  gather_facts: false
  vars_files:
    - vars.yml
    - secrets.yml
  tasks:

    - name: Get iso storage directory
      community.general.proxmox_storage_info:
        api_host: "{{ pve_api_host }}"
        api_user: "{{pve_iaac_name}}@pam"
        api_password: "{{ pve_iaac_password }}"
        storage: "{{ pve_iso_storage }}"
      register: iso_store
        
    - name: Set templates storage path value
      ansible.builtin.set_fact:
        pve_iso_dir: "{{ iso_store.proxmox_storages[0].path}}/template/iso"

    - name: Get snippets storage directory
      community.general.proxmox_storage_info:
        api_host: "{{ pve_api_host }}"
        api_user: "{{pve_iaac_name}}@pam"
        api_password: "{{ pve_iaac_password }}"
        storage: "{{ pve_snippets_storage }}"
      register: snippets_store

    - name: Set snippets storage path value
      ansible.builtin.set_fact:
        pve_snippets_dir: "{{ snippets_store.proxmox_storages[0].path}}/snippets"


    - name: Download cloud images
      ansible.builtin.get_url:
        url: "{{ item.value.iso_url }}"
        dest: "{{ pve_iso_dir }}/{{ item.value.iso_url | basename | splitext | first }}.img"
        checksum: "{{ item.value.checksum_algorithm }}:{{ lookup('ansible.builtin.url', item.value.checksum_url) | regex_search(item.value.checksum_regexp, '\\1') | first}}"
        validate_certs: true
        timeout: 60
      loop: "{{ templates | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Create default cloudinit config
      ansible.builtin.template:
        src: default_cloudconfig.yml.j2
        dest: "{{ pve_snippets_dir }}/default_cloudconfig.yml"

    - name: Create vm for tempalte
      community.general.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_iaac_name }}@pam"
        api_password: "{{ pve_iaac_password }}"
        node: "{{ node }}"
        vmid: "{{ item.value.vmid }}"
        name: "{{ item.value.name }}"
        storage: "{{ pve_template_storage }}"
        cores: 2
        memory: 2048
        ide:
          ide2: "{{ pve_template_storage }}:cloudinit,format=raw"
        net:
          net0: virtio,bridge=vmbr0
        ipconfig:
          ipconfig0: ip=dhcp
        cicustom: "vendor={{ pve_snippets_storage }}:snippets/default_cloudconfig.yml"
        agent: true
        ostype: l26
        scsihw: virtio-scsi-pci
        boot: c
        bootdisk: virtio0
        template: true
        state: present
      loop: "{{ templates | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Import images to disk
      community.general.proxmox_disk:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_root_name }}@pam"
        api_password: "{{ pve_root_password }}"
        vmid: "{{ item.value.vmid }}"
        import_from: "{{ pve_iso_dir }}/{{ item.value.iso_url | basename | splitext | first }}.img"
        format: "{{ disk_format }}"
        disk: virtio0
        storage: "{{ pve_template_storage }}"
        state: present
        timeout: 60 # 1 minute
      loop: "{{ templates | dict2items }}"
      loop_control:
        label: "{{ item.key }}"