---
- name: Download current Arch Linux Cloud Image
  hosts: localhost
  gather_facts: true
  become_user: bsmits
  vars_files:
    - ~/secrets/creds.yml
  vars:
    ansible_become_pass: "{{ become_password }}"
    cloud_init_force_download: false
    cloud_init_img_download_version: noble
    cloud_init_template_name: golden-archlinux-2024.12.01

  tasks:
    - include_role:
        name: arch_init
  tags:
    - download

- name: Proxmox tasks
  hosts: proxmox_prd
  gather_facts: true
  become: true
  vars_files:
    - ~/secrets/creds.yml
  vars:
    ansible_become_pass: "{{ become_password }}"
    var_api_host: proxmox-prd.devopsfables.net
    var_api_user: root@pam
    var_api_token_id: "{{ vault_api_token_id }}"
    var_api_token_secret: "{{ vault_api_token_secret }}"

  tasks:
    - include_role:
        name: proxmox
        tasks_from: ../roles/proxmox/tasks/proxmox-tasks.yml
  tags:
    - proxmox
