---
# Local Host Tasks
- name: Register if a recent Cloud-init image exists
  ansible.builtin.find:
    paths: "{{ cloud_init_img_target_path }}/"
    pattern: "{{ cloud_init_img_file_name }}.img"
    age: -7d
  register: file_data

- name: If the downloaded image is older than 7 days, redownload it
  when: not file_data.files | length > 0 or cloud_init_force_download
  block:
    - name: Download cloud image
      ansible.builtin.get_url:
        url: "{{ cloud_init_img_source_url }}"
        dest: "{{ cloud_init_img_target_path }}"
        mode: "0655"

    - name: Virt-customize the image
      ansible.builtin.shell: |
        cd {{ cloud_init_img_target_path }}
        virt-customize -a {{ cloud_init_img_target_name }}.img --install qemu-guest-agent
        virt-customize -a {{ cloud_init_img_target_name }}.img --install python3
        virt-customize -a {{ cloud_init_img_target_name }}.img --run-command 'systemctl enable qemu-guest-agent'
        virt-customize -a {{ cloud_init_img_target_name }}.img --run-command 'systemctl stop qemu-guest-agent'
        virt-customize -a {{ cloud_init_img_target_name }}.img --root-password password:ubuntu
      become: true

    - name: Rename the image file
      ansible.builtin.shell: |
        mv {{ cloud_init_img_target_path }}/{{ cloud_init_img_target_name }}.img {{ cloud_init_img_file_path }}/{{ cloud_init_img_file_name }}.img
