---
- name: Download Cloud Images
  hosts: localhost
  gather_facts: true
  become_user: bsmits
  vars_files:
    - ~/secrets/creds.yml
  vars:
    ansible_become_pass: "{{ become_password }}"
    cloud_init_force_download: true
    # Ubuntu specific vars
    ubuntu_cloud_init_img_download_version: noble
    ubuntu_cloud_init_template_name: golden-ubuntu-24.04.1
    # Arch specific vars
    arch_cloud_init_template_name: golden-arch-latest
  roles:
  - ubuntu_init
  - arch_init
  tasks:
    - include_role:
        name: ubuntu_init
      tags:
        - download
        - ubuntu

    - include_role:
        name: arch_init
      tags:
        - download
        - arch

- name: Proxmox tasks
  hosts: proxmox_prd
  gather_facts: true
  become: true
  vars_files:
    - ~/secrets/creds.yml
  vars:
    ansible_become_pass: "{{ become_password }}"
    var_api_host: proxmox-prd.devopsfables.net
    var_api_user: root@pam
    var_api_token_id: "{{ vault_api_token_id }}"
    var_api_token_secret: "{{ vault_api_token_secret }}"
    cloud_init_ciuser: ansibleadmin
    cloud_init_storage_target: LVM-Prime
    cloud_init_disksize: 20G
    
    # Define the template names here
    ubuntu_cloud_init_template_name: golden-ubuntu-24.04.1
    arch_cloud_init_template_name: golden-arch-latest
    
    # OS-specific settings
    os_settings:
      ubuntu:
        template_name: "{{ ubuntu_cloud_init_template_name }}"
        vmid: 9999
      arch:
        template_name: "{{ arch_cloud_init_template_name }}"
        vmid: 9998
    
    # Set active OS based on tags
    active_os: "{{ 'arch' if 'arch' in ansible_run_tags else 'ubuntu' }}"
    
    # Use the active OS settings
    cloud_init_template_name: "{{ os_settings[active_os].template_name }}"
    cloud_init_template_vmid: "{{ os_settings[active_os].vmid }}"
  
  tasks:
    - include_role:
        name: proxmox
  tags:
    - create

#   # This is a test to see if the VM is created and started, it can remain commented out unless testing of the templte is desired.
#   # Use the command 'ansible-playbook ubuntu-golden-image.yaml --tags test' to run this task alone.
# - name: start test vm
#   hosts: proxmox_prd
#   vars_files:
#     - ~/secrets/creds.yml
#   vars:
#     #ansible_become_pass: "{{ vault_api_password }}"
#     var_vm_name: test-vm
#   tasks:
#     - name: Clone and start test vm
#       community.general.proxmox_kvm:
#         node: proxmox
#         api_user: root@pam
#         api_host: proxmox-prd.devopsfables.net
#         api_token_id: "{{ vault_api_token_id }}"
#         api_token_secret: "{{ vault_api_token_secret }}"
#         clone: golden-ubuntu-24.04.1
#         name: "{{ var_vm_name }}"
#         timeout: 500
#       register: start_result



#     - name: Start the cloned VM
#       community.general.proxmox_kvm:
#         node: proxmox
#         api_user: root@pam
#         api_host: proxmox-prd.devopsfables.net
#         api_token_id: "{{ vault_api_token_id }}"
#         api_token_secret: "{{ vault_api_token_secret }}"
#         vmid: "{{ start_result.vmid }}"
#         state: started
#         timeout: 500
#       when: start_result is success
    
#     - name: Print start result
#       ansible.builtin.debug:
#         var: start_result
#   tags:
#     - test
